# Generated by Django 5.1 on 2024-10-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tovar',
            options={'permissions': [('with discount', 'Can set discount')], 'verbose_name_plural': 'Tovarlar'},
        ),
        migrations.AddField(
            model_name='tovar',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Chegirma'),
        ),
    ]
